config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'workouts#index'
  resources :workouts, only: [:show, :create, :new, :edit, :destroy, :update] #display all the routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
before_action :decide_entry_detail, only: :create

def index
  @workouts=Workout.all.order("created_at DESC")
end

def show
  @workout=Workout.find(params[:id])
end

def new
  @workout=Workout.new
end

def create
  @workout=Workout.new(workout_params)
  @workout.date=Date.new(params[:workout]['date(1i)'].to_i, params[:workout]['date(2i)'].to_i, params[:workout]['date(3i)'].to_i)
  if @workout.save
    redirect_to @workout#article show page
  else
    render 'new'#if the form saving fails display the same form again
  end
end

def edit
  @workout = Workout.find(params[:id])
end

def update
  @workout = Workout.find(params[:id])
  if @workout.update(params.require(:workout).permit(:date, :workout, :mood, :length))
    redirect_to @workout#article show page
  else
    render 'edit'
  end
end

def destroy
  @workout = Workout.find(params[:id])
  @workout.destroy
  redirect_to root_path
end

private

def workout_params
  params.require(:workout).permit(:date, :workout, :mood, :length, :entry_details)
end

def decide_entry_detail
  current_date=Date.today
  entered_date=Date.new(params[:workout]['date(1i)'].to_i, params[:workout]['date(2i)'].to_i, params[:workout]['date(3i)'].to_i)

  if entered_date < current_date
    params[:workout][:entry_details]='Late Entry'
  elsif entered_date > current_date
    params[:workout][:entry_details]='Early Entry'
  else
    params[:workout][:entry_details]='On Time'
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Details</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register",  new_user_registration_path, method: :get%>
      <%= link_to "Login",  new_user_session_path, method: :get %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/workouts/edit.html.erb
<div class="container">
  <div class="jumbotron">

    <h1>Edit Workout</h1>

    <%= form_with(model: @workout, local: true) do |form| %>

      <p>
        <%= form.label :"Date" %><br>
        <%= form.date_select :date %>
      </p>

      <p>
        <%= form.label :"What did you workout?" %><br>
        <%= form.text_area :workout %>
      </p>

      <p>
        <%= form.label :"How was your mood?" %><br>
        <%= form.text_area :mood %>
      </p>

      <p>
        <%= form.label :"How long did you workout?" %><br>
        <%= form.text_area :length %>
      </p>

      <p>
        <%= form.submit %>
      </p>
    <% end %>



  </div>
</div>

app/views/workouts/index.html.erb
  <div class="container" align="center">
    <h1>Gym Workout Schedule</h1>
  <div class="jumbotron">


<table>
  <tr>
    <th style="color:black">Workout</th>
    <th style="color:black">Action1</th>
    <th style="color:black">Action2</th>
    <th style="color:black">Action3</th>
  </tr>

  <% @workouts.each do |workout| %>
    <tr>

      <td><%= workout.workout %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>

      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>

      <td><%= link_to 'Delete', workout_path(workout), method: :delete, data: { confirm: 'Are you sure you want to delete the record?' }  %></td>
      </tr>
  <% end %>
</table>

</div>
</div>

app/views/workouts/new.html.erb
<div class="container">
  <div class="jumbotron">


    <%= form_with scope: :workout, url: workouts_path, local: true do |form| %>


      <p>
        <%= form.label :"Date" %><br>
        <%= form.date_select :date %>
      </p>

      <p>
        <%= form.label :"What did you workout?" %><br>
        <%= form.text_area :workout %>
      </p>

      <p>
        <%= form.label :"How was your mood?" %><br>
        <%= form.text_area :mood %>
      </p>

      <p>
        <%= form.label :"How long did you workout?" %><br>
        <%= form.text_area :length %>
      </p>

      <p>
        <%= form.submit %>
      </p>
    <% end %>

  </div>

</div>

app/views/workouts/show.html.erb
<div class="container">
  <div class="jumbotron">
    <p>
      <strong>Date:</strong>
      <%= @workout.date%>
    </p>

    <p>
      <strong>Workout:</strong>
      <%= @workout.workout %>
    </p>

    <p>
      <strong>Mood:</strong>
      <%= @workout.mood %>
    </p>


    <p>
      <strong>Duration:</strong>
      <%= @workout.length %>
    </p>


    <p>
      <strong>Entry Details:</strong>
      <%= @workout.entry_details %>
    </p>
  </div>

</div>